Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.synced_folder "/home/ofca/Projects/QuoyServer/", "/vagrant/quoy_server"
      config.vbguest.auto_update = false
  end